services:
  postgres:
    container_name: dk_postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: dk_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - '5050:80'
volumes:
  postgres_data:
  pgadmin_data:


# acesso postgres no docker
# passo 1: http://localhost:5050/browser/
# passo 2: user = admin and pwd = pass
# passo 3: criar um novo register / server
# tab 1 : docker-postgres
# tab 2 : connection : nome do docker do postgres (dk_postgres) e user : docker / pwd : docker